name: "Watchdog Detekt Action"
description: "Run Detekt from a centralized location"
inputs:
  github-token:
    description: "Github token used for generating releases"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download Detekt Configuration
      run: |
        project_type="${{ inputs.project-type }}"
        echo "project type = $project_type"
        if [ "$project_type" == "ktor" ]; then
          echo 'Downloading ktor configuration'
          curl -L -o ktor-detekt.yml https://raw.githubusercontent.com/monta-app/detekt-action/main/conf/ktor-detekt.yml
        else
          echo 'Downloading micronaut configuration'
          curl -L -o detekt.yml https://raw.githubusercontent.com/monta-app/detekt-action/main/conf/detekt.yml
        fi
        ls -a
      shell: bash
    - name: Run Detekt
      uses: alaegin/Detekt-Action@v1.22.0
      with:
        github_token: ${{ inputs.github-token }}
        detekt_config: detekt.yml
