name: "Watchdog Detekt Action"
description: "Run Detekt from a centralized location"
inputs:
  github-token:
    description: "Github token used for generating releases"
    required: true
  project-config-overrides:
    description: "Override configuration with project specific overrides - point to a config file in '.yml' format"
    required: false
    type: string
runs:
  using: "composite"
  steps:
    - name: Download cURL & update Git
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
        sudo apt-get install -y git
      shell: bash
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download Detekt Configuration
      run: |
        echo 'Downloading configuration'
        curl -L -o detekt.yml https://raw.githubusercontent.com/monta-app/detekt-action/main/conf/detekt.yml
        ls -a
      shell: bash
    - name: Run Detekt
      if: ${{ !inputs.project-config-overrides }}
      uses: alaegin/Detekt-Action@v1.23.6
      with:
        github_token: ${{ inputs.github-token }}
        detekt_config: detekt.yml
    - name: Run Detekt
      if: ${{ inputs.project-config-overrides }}
      uses: alaegin/Detekt-Action@v1.23.6
      with:
        github_token: ${{ inputs.github-token }}
        detekt_config: detekt.yml,${{ inputs.project-config-overrides }}
