name: "Watchdog Detekt Action"
description: "Run Detekt from a centralized location"
inputs:
  github-token:
    description: "Github token used for generating releases"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download cURL
      run: |
        sudo apt-get update
        sudo apt-get install -y curl
      shell: bash
    - name: Download Detekt Configuration
      run: |
        echo 'Downloading configuration'
        curl -L -o detekt.yml https://raw.githubusercontent.com/monta-app/detekt-action/main/conf/detekt.yml
        ls -a
      shell: bash
    - name: Run Detekt
      uses: alaegin/Detekt-Action@v1.23.5
      with:
        github_token: ${{ inputs.github-token }}
        detekt_config: detekt.yml
